services:
  - type: web
    name: couple-sync-video-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 70